/**
 * MIT License
 *
 * Copyright (c) 2019-2026 WenyanLiu (https://github.com/WenyanLiu/CCFrank4dblp)
 *
 * SCI ranking badge (中科院期刊分区表升级版 2025), data generated by
 * build/gen_sci_data.py. Journals only — the CAS table does not rank
 * conferences, so conference urls render an empty badge.
 */

const sci = {};

sci.zoneNames = { 1: "1区", 2: "2区", 3: "3区", 4: "4区" };

// Metadata services may resolve a journal by ISSN even when the returned name
// differs from the local table. Cache that verified mapping for this page.
sci.runtimeMetaByName = {};

// lazy name -> meta index for "publication" lookups (Web of Science pages)
sci.nameIdx = null;

sci.normName = function (s) {
  return String(s)
    .toLowerCase()
    .replace(/[^a-z0-9\u4e00-\u9fff]+/g, " ")
    .trim();
};

sci.buildNameIdx = function () {
  if (sci.nameIdx !== null) return sci.nameIdx;
  sci.nameIdx = {};
  for (let key in ccf.sciMeta) {
    let meta = ccf.sciMeta[key];
    sci.nameIdx[sci.normName(meta.n)] = meta;
  }
  return sci.nameIdx;
};

/**
 * Look up the CAS ranking meta of a dblp journal url.
 * @param {string} url - e.g. "/journals/tocs/tocs" or stream "/journals/tocs"
 * @returns {object|null} meta object or null when unknown
 */
sci.getMeta = function (url) {
  if (!url) return null;
  let key = ccf.sciRankUrl[url];
  if (key === undefined && url.indexOf("/journals/") == 0) {
    // tolerate sub-key variants like "/journals/jeric/jeric": fall back to
    // the standard "<stream>/<stream>" form, then to the stream itself
    let parts = url.split("/");
    if (parts.length >= 4) {
      key = ccf.sciRankUrl["/journals/" + parts[2] + "/" + parts[2]];
    }
    if (key === undefined) {
      key = ccf.sciRankUrl[parts.slice(0, 3).join("/")];
    }
  }
  if (key === undefined) return null;
  return ccf.sciMeta[key];
};

/**
 * Name-based lookup covering the FULL CAS table (all disciplines, not only
 * dblp-indexed journals). rankNameIdx values are compact arrays:
 * [zone, top, category, wosType, position, warning].
 */
sci.getMetaByName = function (name) {
  if (!name) return null;
  const key = ccf.normName(name);
  if (sci.runtimeMetaByName[key]) return sci.runtimeMetaByName[key];
  const arr = ccf.sciNameIdx ? ccf.sciNameIdx[key] : null;
  if (arr) {
    return {
      z: arr[0],
      t: arr[1],
      c: arr[2],
      w: arr[3],
      p: arr[4],
      warn: arr[5],
      n: name,
    };
  }
  return sci.buildNameIdx()[key] || null;
};

/** Exact lookup by normalized ISSN (digits + X), from metadata services. */
sci.getMetaByIssn = function (issnKey, journal) {
  const arr = ccf.sciIssnIdx ? ccf.sciIssnIdx[issnKey] : null;
  if (!arr) return null;
  const meta = {
    z: arr[0],
    t: arr[1],
    c: arr[2],
    w: arr[3],
    p: arr[4],
    warn: arr[5],
    n: journal || issnKey,
  };
  if (journal) sci.runtimeMetaByName[ccf.normName(journal)] = meta;
  return meta;
};

sci.getRankInfo = function (refine, type) {
  let rankInfo = {};
  rankInfo.ranks = [];
  rankInfo.info = "";
  let meta = null;
  if (type == "url") {
    meta = sci.getMeta(refine);
    if (!meta && ccf.rankFullName && ccf.rankFullName[refine]) {
      meta = sci.getMetaByName(ccf.rankFullName[refine]);
    }
  } else if (type == "publication") {
    meta = sci.getMetaByName(refine);
  }
  rankInfo.meta = meta;
  if (meta == null) {
    rankInfo.ranks.push("none");
    rankInfo.info += "Not Found in 中科院分区表2025\n";
  } else {
    rankInfo.ranks.push(meta.z);
    rankInfo.info += meta.n + "\n";
    rankInfo.info += "中科院分区表2025升级版: " + meta.c + " " + sci.zoneNames[meta.z];
    if (meta.p) {
      rankInfo.info += " (" + meta.p + ")";
    }
    rankInfo.info += "\n";
    if (meta.t) {
      rankInfo.info += "Top期刊: 是\n";
    }
    if (meta.s) {
      rankInfo.info += "小类1: " + meta.s[0] + " " + sci.zoneNames[meta.s[1]] + "\n";
    }
    rankInfo.info += "WoS收录: " + meta.w + "\n";
    if (meta.warn) {
      rankInfo.info += "⚠ 国际期刊预警名单\n";
    }
  }
  return rankInfo;
};

sci.getRankClass = function (ranks) {
  let rank = ranks[0];
  if (rank >= "1" && rank <= "4") {
    return "sci-" + rank;
  }
  return "sci-none";
};

sci.getRankSpan = function (refine, type, rawUrl) {
  // journals only: suppress the badge for conference venues and for
  // venue abbreviations we cannot resolve to a journal reliably
  if (type == "abbr" || type == "meeting") {
    if (!rawUrl) return $("<span>").addClass("ccf-rank-hidden");
    type = "url";
    refine = rawUrl;
  }
  if (type == "url" && !refine) {
    return $("<span>").addClass("ccf-rank-hidden");
  }
  let rankInfo = sci.getRankInfo(refine, type);
  let isConf = typeof refine == "string" && refine.indexOf("/conf/") == 0;
  if (rankInfo.ranks[0] == "none" && (isConf || type != "url")) {
    return $("<span>").addClass("ccf-rank-hidden");
  }
  let span = $("<span>")
    .addClass("ccf-rank")
    .addClass(sci.getRankClass(rankInfo.ranks));
  let firstRank = rankInfo.ranks[0];
  if (firstRank == "none") {
    span.text("SCI None");
  } else {
    span.text("SCI " + sci.zoneNames[firstRank]);
    if (rankInfo.meta && rankInfo.meta.t) {
      span.addClass("sci-top");
    }
  }
  if (rankInfo.info.length != 0) {
    span
      .addClass("ccf-tooltip")
      .append($("<pre>").addClass("ccf-tooltiptext").text(rankInfo.info));
  }
  return span;
};
