/**
 * MIT License
 *
 * Copyright (c) 2019-2026 WenyanLiu (https://github.com/WenyanLiu/CCFrank4dblp)
 *
 * XinRui (新锐期刊分区表 2026) badge, data generated by build/gen_sci_data.py.
 * Covers journals plus the small conference table shipped with the XinRui
 * ranking (ACL/CVPR/ICML/... stored as conf entries in xrRankUrlMeta.js).
 */

const xr = {};

xr.zoneNames = { 1: "1区", 2: "2区", 3: "3区", 4: "4区" };
xr.runtimeMetaByName = {};

// lazy name -> meta index for "publication" lookups (Web of Science pages)
xr.nameIdx = null;

xr.normName = function (s) {
  return String(s)
    .toLowerCase()
    .replace(/[^a-z0-9\u4e00-\u9fff]+/g, " ")
    .trim();
};

xr.buildNameIdx = function () {
  if (xr.nameIdx !== null) return xr.nameIdx;
  xr.nameIdx = {};
  for (let key in ccf.xrMeta) {
    let meta = ccf.xrMeta[key];
    if (meta.conf) continue;
    xr.nameIdx[xr.normName(meta.n)] = meta;
  }
  return xr.nameIdx;
};

/**
 * Look up the XinRui ranking meta of a dblp url (journal or conference).
 * @param {string} url - e.g. "/journals/tocs/tocs" or "/conf/acl/acl"
 * @returns {object|null} meta object or null when unknown
 */
xr.getMeta = function (url) {
  if (!url) return null;
  let key = ccf.xrRankUrl[url];
  if (key === undefined && url.indexOf("/journals/") == 0) {
    let parts = url.split("/");
    if (parts.length >= 4) {
      key = ccf.xrRankUrl["/journals/" + parts[2] + "/" + parts[2]];
    }
    if (key === undefined) {
      key = ccf.xrRankUrl[parts.slice(0, 3).join("/")];
    }
  }
  if (key === undefined) return null;
  return ccf.xrMeta[key];
};

/**
 * Name-based lookup covering the FULL XinRui table (all disciplines).
 * rankNameIdx values are compact arrays: [zone, top, category, db, warning].
 */
xr.getMetaByName = function (name) {
  if (!name) return null;
  const key = ccf.normName(name);
  if (xr.runtimeMetaByName[key]) return xr.runtimeMetaByName[key];
  const arr = ccf.xrNameIdx ? ccf.xrNameIdx[key] : null;
  if (arr) {
    return { z: arr[0], t: arr[1], c: arr[2], db: arr[3], warn: arr[4], n: name };
  }
  return xr.buildNameIdx()[key] || null;
};

/** Exact lookup by normalized ISSN (digits + X), from metadata services. */
xr.getMetaByIssn = function (issnKey, journal) {
  const arr = ccf.xrIssnIdx ? ccf.xrIssnIdx[issnKey] : null;
  if (!arr) return null;
  const meta = { z: arr[0], t: arr[1], c: arr[2], db: arr[3], warn: arr[4], n: journal || issnKey };
  if (journal) xr.runtimeMetaByName[ccf.normName(journal)] = meta;
  return meta;
};

xr.getRankInfo = function (refine, type) {
  let rankInfo = {};
  rankInfo.ranks = [];
  rankInfo.info = "";
  let meta = null;
  if (type == "url") {
    meta = xr.getMeta(refine);
    if (!meta && ccf.rankFullName && ccf.rankFullName[refine]) {
      meta = xr.getMetaByName(ccf.rankFullName[refine]);
    }
  } else if (type == "publication") {
    meta = xr.getMetaByName(refine);
  } else if (type == "abbr" || type == "meeting") {
    // venue abbreviations: only the XinRui conference table is mapped
    let abbr = String(refine || "").toUpperCase().replace(/[^A-Z0-9&]/g, "");
    let confUrl = ccf.xrConfAbbr ? ccf.xrConfAbbr[abbr] : undefined;
    if (confUrl) {
      meta = ccf.xrMeta[confUrl];
    }
  }
  rankInfo.meta = meta;
  if (meta == null) {
    rankInfo.ranks.push("none");
    rankInfo.info += "Not Found in 新锐期刊分区表2026\n";
  } else {
    rankInfo.ranks.push(meta.z);
    if (meta.conf) {
      rankInfo.info += meta.conf + " (会议)\n";
      rankInfo.info += "新锐期刊分区表2026会议表: " + xr.zoneNames[meta.z] + " Top\n";
    } else {
      if (meta.cn) {
        rankInfo.info += meta.cn + "\n";
      }
      rankInfo.info += meta.n + "\n";
      rankInfo.info += "新锐期刊分区表2026: " + meta.c + " " + xr.zoneNames[meta.z] + "\n";
      if (meta.t) {
        rankInfo.info += "Top期刊: 是\n";
      }
      rankInfo.info += "数据库: " + meta.db + "\n";
      if (meta.warn) {
        rankInfo.info += "⚠ Under Review\n";
      }
    }
  }
  return rankInfo;
};

xr.getRankClass = function (ranks) {
  let rank = ranks[0];
  if (rank >= "1" && rank <= "4") {
    return "xr-" + rank;
  }
  return "xr-none";
};

xr.getRankSpan = function (refine, type, rawUrl) {
  let lookupType = type;
  let lookupRef = refine;
  if (type == "abbr" || type == "meeting") {
    if (rawUrl) {
      // fetchRank abbr path carries the dblp stream url for journal venues
      lookupType = "url";
      lookupRef = rawUrl;
    } else if (!ccf.xrConfAbbr) {
      return $("<span>").addClass("ccf-rank-hidden");
    }
  }
  if (type == "url" && !refine) {
    return $("<span>").addClass("ccf-rank-hidden");
  }
  let rankInfo = xr.getRankInfo(lookupRef, lookupType);
  let isConf =
    rankInfo.meta && rankInfo.meta.conf
      ? true
      : typeof lookupRef == "string" && lookupRef.indexOf("/conf/") == 0;
  if (rankInfo.ranks[0] == "none" && (isConf || type == "abbr" || type == "meeting")) {
    return $("<span>").addClass("ccf-rank-hidden");
  }
  let span = $("<span>")
    .addClass("ccf-rank")
    .addClass(xr.getRankClass(rankInfo.ranks));
  let firstRank = rankInfo.ranks[0];
  if (firstRank == "none") {
    span.text("新锐 None");
  } else {
    span.text("新锐" + xr.zoneNames[firstRank]);
    if (rankInfo.meta && rankInfo.meta.t) {
      span.addClass("xr-top");
    }
  }
  if (rankInfo.info.length != 0) {
    span
      .addClass("ccf-tooltip")
      .append($("<pre>").addClass("ccf-tooltiptext").text(rankInfo.info));
  }
  return span;
};
